services:
  - type: web
    name: central-relatorios-backend
    env: node
    plan: starter
    buildCommand: npm install && npx playwright install --with-deps chromium
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DEMO_MODE
        value: true
      - key: HEADLESS
        value: true
      - key: REPORT_DIR
        value: ./relatorios
      - key: LINHAS_POR_PAGINA
        value: 3000
      - key: SISTEMA_URL
        value: https://floragold.acessocloud.com/index.php
      - key: CORS_ORIGIN
        value: "*"
      - key: AUTO_PAUSE
        value: false
      - key: WAIT_FOR_CALL_FINISH
        value: false
      - key: JOB_TTL_MINUTES
        value: 180
